[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_swap = "9CcZgrQxu4UE72Z7DqFxoGxkhicvqKNWmNbThtPRz62a"
[programs.devnet]
solana_swap = "9CcZgrQxu4UE72Z7DqFxoGxkhicvqKNWmNbThtPRz62a"

[registry]
url = "https://api.apr.dev"


[provider]
cluster = "Localnet"
wallet = "/Users/ted.nguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
