[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_swap = "GhYNz1LcUJgRYC6D6Qn4jfkAg7hgTrzuoT53QcnmJb5V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ted.nguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
